# Generated by Django 5.1.3 on 2024-12-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('in', 'UANG MASUK'), ('out', 'UANG KELUAR')], default='in', max_length=20, verbose_name='Type Transaction'),
        ),
    ]
