# Generated by Django 5.1.3 on 2024-12-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_discount_jobcategory_service_user_saldo_worker_saldo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='Service',
            new_name='service',
        ),
    ]
