# Generated by Django 5.1.3 on 2024-12-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_time',
            new_name='created_at',
        ),
    ]
