# Generated by Django 5.1.3 on 2024-12-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
