# Generated by Django 5.1.3 on 2024-12-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_service_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Promo Code')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Percentage')),
                ('min_transaction', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Minimum Transaction')),
                ('max_usage', models.PositiveIntegerField(verbose_name='Max Usage')),
                ('usage_quota', models.PositiveIntegerField(default=0, verbose_name='Usage Quota')),
                ('voucher_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Voucher Price')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Menunggu Pembayaran'), ('SEARCHING_WORKER', 'Mencari Pekerja Terdekat'), ('WORKER_FOUND', 'Mendapatkan Pekerja'), ('IN_PROGRESS', 'Dikerjakan'), ('COMPLETED', 'Selesai')], default='AWAITING_PAYMENT', max_length=20, verbose_name='Order Status')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myapp.discount', verbose_name='Discount')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.service', verbose_name='Service')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myapp.worker', verbose_name='Worker')),
            ],
        ),
    ]
