# Generated by Django 5.1.3 on 2024-12-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
