# Generated by Django 5.1.3 on 2024-12-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_discount_expired_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pembelian')),
                ('is_used', models.BooleanField(default=False, verbose_name='Telah Digunakan')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_vouchers', to='myapp.discount', verbose_name='Diskon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='myapp.user', verbose_name='Pembeli')),
            ],
        ),
    ]
